# Write a Python program to create a tensor of shape (3, 3) filled with random numbers between 0 and 1

In [6]:
import tensorflow as tf

In [7]:
tensor=tf.random.uniform(shape=(3,3),minval=0,maxval=1)

In [8]:
print("Random Tensor:")
print(tensor)

Random Tensor:
tf.Tensor(
[[0.42725348 0.44824672 0.02445781]
 [0.88342464 0.30956066 0.30148685]
 [0.4087962  0.747723   0.467749  ]], shape=(3, 3), dtype=float32)


# Perform basic tensor operations including matrix addition, multiplication, and transpose.

In [9]:
A = tf.random.uniform((3, 3), minval=0, maxval=1)
B = tf.random.uniform((3, 3), minval=0, maxval=1)

In [10]:
print("Tensor A:",A)
print("Tensor B:",B)

Tensor A: tf.Tensor(
[[0.51623607 0.72765636 0.4044522 ]
 [0.6386578  0.18500972 0.96143353]
 [0.85817206 0.722702   0.26664126]], shape=(3, 3), dtype=float32)
Tensor B: tf.Tensor(
[[0.40134525 0.42341244 0.4555148 ]
 [0.2960267  0.46026075 0.3813144 ]
 [0.28455877 0.9405693  0.55091023]], shape=(3, 3), dtype=float32)


In [11]:
# Matrix Addition
add_result = tf.add(A, B)
print("Matrix Addition (A + B):")
print(add_result)

Matrix Addition (A + B):
tf.Tensor(
[[0.9175813  1.1510688  0.859967  ]
 [0.9346845  0.64527047 1.3427479 ]
 [1.1427308  1.6632713  0.8175515 ]], shape=(3, 3), dtype=float32)


In [12]:
# Multiplication
mul_result = tf.matmul(A, B)
print("Matrix Multiplication (A x B):")
print(mul_result)

Matrix Multiplication (A x B):
tf.Tensor(
[[0.53768504 0.93390775 0.7354359 ]
 [0.5846745  1.2598633  0.89112854]
 [0.63423747 0.9467867  0.81338215]], shape=(3, 3), dtype=float32)


In [13]:
# Transpose
transpose_A = tf.transpose(A)
print("Transpose of Tensor A:")
print(transpose_A)

Transpose of Tensor A:
tf.Tensor(
[[0.51623607 0.6386578  0.85817206]
 [0.72765636 0.18500972 0.722702  ]
 [0.4044522  0.96143353 0.26664126]], shape=(3, 3), dtype=float32)


# Convert the resulting tensor into a NumPy array and then reshape it into a (1, 9) tensor.

In [14]:
tensor=tf.random.uniform(shape=(3,3),minval=0,maxval=1)
print("Original Tensor:",tensor)

Original Tensor: tf.Tensor(
[[0.505924   0.8106413  0.01334965]
 [0.69783616 0.43383288 0.9185262 ]
 [0.76320827 0.84339523 0.0231812 ]], shape=(3, 3), dtype=float32)


In [15]:
numpy_array=tensor.numpy()
print("Converted Numpy array:",numpy_array)

Converted Numpy array: [[0.505924   0.8106413  0.01334965]
 [0.69783616 0.43383288 0.9185262 ]
 [0.76320827 0.84339523 0.0231812 ]]


In [16]:
reshaped_tensor=tf.reshape(tensor,(1,9))
print("Reshaped Tensor:",reshaped_tensor)

Reshaped Tensor: tf.Tensor(
[[0.505924   0.8106413  0.01334965 0.69783616 0.43383288 0.9185262
  0.76320827 0.84339523 0.0231812 ]], shape=(1, 9), dtype=float32)
